export const registrationLabelMap = {
  to_register: "A cadastrar",
  registered_waiting_card: "Aguardando carteirinha",
  card_saved: "Cadastro confirmado",
};

export const intakeStatusLabelMap = {
  pending: "Pendente",
  updated: "Atualização pendente",
  pending_exclusion: "Exclusão pendente",
  reminded: "Lembrete enviado",
  resolved: "Resolvido",
  terminated: "Demitido",
};

const LABEL_MAP = {
  id: "ID",
  SUB: "SUB",
  NOME: "Nome",
  CARGO_DO_TITULAR: "Cargo do titular",
  NOME_DO_DEPENDENTE: "Nome do dependente",
  VINCULO_FAMILIAR: "Vínculo familiar",
  NASCIMENTO: "Nascimento",
  MATRICULA: "Matrícula",
  CPF_TIT: "CPF titular",
  CPF_DEP: "CPF dependente",
  TIPO: "Tipo",
  NUMERO_DO_DOCUMENTO: "Número do documento",
  NATUREZA_DA_IDENTIFICACAO: "Natureza da identificação",
  ORGAO_EXPEDIDOR: "Órgão expedidor",
  PAIS_EXPEDIDOR: "País expedidor",
  DATA_DE_EXPEDICAO: "Data de expedição",
  SEXO: "Sexo",
  ESTADO_CIVIL: "Estado civil",
  ADMISSAO: "Admissão",
  INICIO_DA_VIGENCIA: "Início da vigência",
  NOME_DA_MAE: "Nome da mãe",
  CEP: "CEP",
  ENDERECO_COMPLETO: "Endereço completo",
  BAIRRO: "Bairro",
  CIDADE: "Cidade",
  UF: "UF",
  CELULAR: "Celular",
  TIPO_DE_CONTA: "Tipo de conta",
  BANCO: "Banco",
  AGENCIA: "Agência",
  CONTA_COM_DIGITO: "Conta com dígito",
  CODIGO_DO_PLANO: "Código do plano",
  CASAMENTO: "Casamento",
  EMAIL_DO_COLABORADOR: "E-mail do colaborador",
  STATUS: "Status",
  AVISO_PREVIO_ATE: "Aviso prévio até",
  CARTEIRINHA: "Carteirinha",
  CARTEIRINHA_SAUDE: "Carteirinha saúde",
  CARTEIRINHA_DENTAL: "Carteirinha dental",
  NO_HEALTH_CARD: "Sem saúde",
  NO_DENTAL_CARD: "Sem dental",
  PLAN_REGISTRATION_STATUS: "Status do cadastro no plano",
  REGISTERED_IN_PLAN_AT: "Cadastrado no plano em",
  CARD_SAVED_AT: "Carteirinhas salvas em",
  ACTIVE: "Ativo",
  CREATED_AT: "Criado em",
  UPDATED_AT: "Atualizado em",
  DEPENDENT_COUNT: "Quantidade de dependentes",
};

export const prettifyLabel = (key) =>
  LABEL_MAP[key] || key.replace(/_/g, " ");